# Generated by Django 3.2.12 on 2022-03-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSalesView',
            fields=[
                ('pointofsale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.pointofsale')),
            ],
            options={
                'abstract': False,
            },
            bases=('shop.pointofsale',),
        ),
        migrations.RemoveField(
            model_name='pointofsale',
            name='address',
        ),
    ]
