# Generated by Django 3.2.12 on 2022-04-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderposition',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='workshop.productionplan'),
        ),
        migrations.AlterField(
            model_name='productiondayproduct',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.productionplan'),
        ),
    ]
