# Generated by Django 4.2.11 on 2024-05-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_product_uom"),
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorderposition",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_positions",
                to="workshop.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="customerordertemplateposition",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_positions",
                to="workshop.product",
                verbose_name="Product",
            ),
        ),
    ]
