# Generated by Django 3.2.12 on 2022-03-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220325_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfSalesView',
        ),
    ]
