# Generated by Django 3.2.12 on 2022-05-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_product_image'),
        ('shop', '0003_auto_20220428_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionday',
            name='day_of_sale',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='productiondayproduct',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_sellable': True}, on_delete=django.db.models.deletion.PROTECT, related_name='production_days', to='workshop.product'),
        ),
        migrations.AlterField(
            model_name='productiondayproduct',
            name='production_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_day_products', to='shop.productionday'),
        ),
        migrations.AlterField(
            model_name='productiondaytemplate',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_sellable': True}, on_delete=django.db.models.deletion.PROTECT, related_name='production_day_templates', to='workshop.product'),
        ),
    ]
