# Generated by Django 3.2.12 on 2022-05-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_product_image'),
        ('shop', '0004_auto_20220512_1536'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productiondayproduct',
            unique_together={('production_day', 'product')},
        ),
    ]
