# Generated by Django 4.2.23 on 2025-10-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_pointofsale_is_primary_alter_pointofsale_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionday",
            name="point_of_sales",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the point of sales where this production day is available.",
                related_name="production_days",
                to="shop.pointofsale",
                verbose_name="Point of Sales",
            ),
        ),
    ]
