# Generated by Django 3.2.12 on 2022-03-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
        ('shop', '0004_delete_pointofsalesview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.address'),
            preserve_default=False,
        ),
    ]
