# Generated by Django 4.2.23 on 2025-10-29 19:09

from django.db import migrations


def create_pos(apps, schema_editor):
    ProductionDay = apps.get_model("shop", "ProductionDay")
    PointOfSale = apps.get_model("shop", "PointOfSale")
    point_of_sales = PointOfSale.objects.all()
    for production_day in ProductionDay.objects.all():
        if not production_day.point_of_sales.exists():
            production_day.point_of_sales.set(point_of_sales)

def remove_pos(apps, schema_editor):
    ProductionDay = apps.get_model("shop", "ProductionDay")
    for production_day in ProductionDay.objects.all():
        production_day.point_of_sales.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productionday_point_of_sales"),
    ]

    operations = [
        migrations.RunPython(create_pos, remove_pos),
    ]