# Generated by Django 3.2.12 on 2022-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_customerorder_production_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionday',
            options={'ordering': ('-day_of_sale',)},
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='order_nr',
        ),
    ]
