# Generated by Django 4.2.23 on 2025-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_add_pos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionday",
            name="point_of_sales",
            field=models.ManyToManyField(
                help_text="Select the point of sales where this production day is available. At least one must be selected.",
                related_name="production_days",
                to="shop.pointofsale",
                verbose_name="Point of Sales",
            ),
        ),
    ]
