# Generated by Django 3.2.12 on 2022-03-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_pointofsaleopeninghour_day_of_the_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofsaleopeninghour',
            options={'ordering': ('day_of_the_week',)},
        ),
    ]
