# Generated by Django 5.2.17 on 2026-08-24 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_alter_productionday_point_of_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="point_of_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="shop.pointofsale",
                verbose_name="Point of Sale",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Street"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="street_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Street Number"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telephone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telephone Number"
            ),
        ),
    ]
