# Generated by Django 3.2.12 on 2022-03-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_pointofsaleopeninghour_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.pointofsale'),
        ),
    ]
