# Generated by Django 3.2.12 on 2022-09-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_pointofsale_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='shop.customerorder'),
        ),
    ]
