# Generated by Django 3.2.12 on 2022-09-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_customerorderposition_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ['-production_day', '-created']},
        ),
    ]
