# Generated by Django 3.2.12 on 2022-03-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220330_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionday',
            options={'ordering': ('day_of_sale',)},
        ),
        migrations.AlterUniqueTogether(
            name='customerorder',
            unique_together={('day_of_sale', 'customer')},
        ),
    ]
