# Generated by Django 3.2.12 on 2022-03-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_category_options'),
        ('shop', '0010_auto_20220330_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionday',
            name='is_open_for_orders',
        ),
        migrations.RemoveField(
            model_name='productionday',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='productionday',
            name='product',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='production_day',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.productionday'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customerorder',
            unique_together={('production_day', 'customer')},
        ),
        migrations.CreateModel(
            name='ProductionDayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('max_quantity', models.PositiveSmallIntegerField()),
                ('is_open_for_orders', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_days', to='workshop.product')),
                ('production_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productionday')),
            ],
            options={
                'ordering': ('production_day',),
            },
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='day_of_sale',
        ),
    ]
