# Generated by Django 3.2.12 on 2022-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_customerorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionday',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
