# Generated by Django 3.2.12 on 2022-11-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorderposition',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='productiondayproduct',
            options={'ordering': ('production_day', 'product')},
        ),
        migrations.AddField(
            model_name='productiondayproduct',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='shop.pointofsale'),
        ),
    ]
