# Generated by Django 3.2.12 on 2022-04-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_customerorder_point_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='production_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productionday'),
        ),
    ]
