# Generated by Django 3.2.12 on 2022-12-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20221125_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.pointofsale'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='shop.pointofsale'),
        ),
        migrations.AlterField(
            model_name='productiondayproduct',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
    ]
