# Generated by Django 3.2.12 on 2023-01-13 09:13

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20221202_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('user__email',)},
        ),
        migrations.AlterField(
            model_name='customerordertemplate',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerordertemplate',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerordertemplate',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
