# Generated by Django 3.2.12 on 2022-04-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_alter_product_description'),
        ('shop', '0015_alter_customerorder_production_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondayproduct',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='workshop.productionplan'),
        ),
    ]
