# Generated by Django 3.2.12 on 2023-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20230113_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderposition',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorderposition',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorderposition',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorderposition',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
