# Generated by Django 3.2.12 on 2022-04-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20220425_1720'),
        ('shop', '0016_productiondayproduct_production_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='workshop.productionplan'),
        ),
        migrations.AlterField(
            model_name='productiondayproduct',
            name='production_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.productionplan'),
        ),
    ]
