# Generated by Django 3.2.12 on 2022-04-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20220425_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiondayproduct',
            name='is_open_for_orders',
        ),
    ]
