# Generated by Django 3.2.12 on 2023-06-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_customerorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
