# Generated by Django 3.2.12 on 2023-06-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0033_alter_product_sku'),
        ('shop', '0021_auto_20230626_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerordertemplate',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='customerordertemplate',
            old_name='to_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='customerordertemplate',
            name='day_of_the_week',
        ),
        migrations.RemoveField(
            model_name='customerordertemplate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customerordertemplate',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='customerordertemplate',
            name='recurrences',
        ),
        migrations.AddField(
            model_name='customerordertemplate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerordertemplate',
            name='orders',
            field=models.ManyToManyField(to='shop.CustomerOrder'),
        ),
        migrations.AddField(
            model_name='customerordertemplate',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='shop.customerordertemplate'),
        ),
        migrations.AlterField(
            model_name='customerorderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerorderposition_positions', to='workshop.product'),
        ),
        migrations.CreateModel(
            name='CustomerOrderTemplatePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('order_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='shop.customerordertemplate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerordertemplateposition_positions', to='workshop.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
