# Generated by Django 3.2.12 on 2023-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20230627_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerordertemplate',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerordertemplate',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
