# Generated by Django 3.2.12 on 2023-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20230628_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordertemplate',
            name='orders',
        ),
        migrations.AddField(
            model_name='customerordertemplateposition',
            name='orders',
            field=models.ManyToManyField(related_name='customer_order_template_positions', to='shop.CustomerOrderPosition'),
        ),
    ]
