# Generated by Django 3.2.12 on 2023-08-17 15:37

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20230811_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderposition',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customerorderposition',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customerorderposition',
            name='price_total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customerorderposition',
            name='price_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True),
        ),
    ]
