# Generated by Django 3.2.12 on 2023-08-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20230817_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionday',
            name='day_of_sale',
            field=models.DateField(unique=True, verbose_name='Day of Sale'),
        ),
        migrations.AlterField(
            model_name='productionday',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
