# Generated by Django 3.2.12 on 2023-08-27 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20230827_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='shop.pointofsale', verbose_name='Point of Sale'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='production_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='shop.productionday', verbose_name='Production Day'),
        ),
    ]
