# Generated by Django 3.2.12 on 2023-08-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0042_alter_instruction_instruction'),
        ('shop', '0028_auto_20230827_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerorderposition_positions', to='workshop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='customerorderposition',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='customerordertemplateposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerordertemplateposition_positions', to='workshop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='customerordertemplateposition',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
    ]
