# Generated by Django 3.2.12 on 2023-09-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20230827_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionday',
            name='day_of_sale',
            field=models.DateField(db_index=True, unique=True, verbose_name='Day of Sale'),
        ),
    ]
