# Generated by Django 3.2.12 on 2022-10-21 08:53
import random
import string

from django.conf import settings
from django.db import migrations

def generate_token():
        alphabet = string.ascii_lowercase + string.digits
        return ''.join(random.choices(alphabet, k=8))

def make_profiles(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Token = apps.get_model('users', 'Token')
    profiles = [Token(user=user, token=generate_token(), ttl=30) for user in User.objects.filter(token__isnull=True)]
    Token.objects.bulk_create(profiles)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_token'),
    ]

    operations = [
        migrations.RunPython(make_profiles),
    ]
