# Generated by Django 3.2.12 on 2023-10-24 15:00

import bakeup.contrib.fields
import bakeup.core.models
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_port', models.PositiveSmallIntegerField(default=25)),
                ('email_use_tls', models.BooleanField(default=False)),
                ('show_full_name_delivery_bill', models.BooleanField(default=True)),
                ('show_remaining_products', models.BooleanField(default=False)),
                ('user_registration_fields', bakeup.contrib.fields.ChoiceArrayField(base_field=models.CharField(choices=[('first_name', 'First name'), ('last_name', 'Last name'), ('point_of_sale', 'Point of sale'), ('street', 'Street'), ('street_number', 'Street number'), ('postal_code', 'Postal code'), ('city', 'City'), ('telephone_number', 'Telephone number')], max_length=24), default=bakeup.core.models.default_registration_fields, size=None)),
                ('language_default', models.CharField(choices=[('de', 'Deutsch'), ('de-DE@formal', 'Deutsch formal'), ('en', 'Englisch')], default='de-DE', max_length=12)),
                ('account_email_verification', models.CharField(choices=[('optional', 'optional'), ('mandatory', 'mandatory'), ('none', 'none')], default='optional', max_length=12)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_text', models.TextField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_day_reminder_subject', models.CharField(default='Deine Bestellung ist abholbereit', max_length=1024)),
                ('production_day_reminder_body', models.TextField(default=bakeup.core.models.get_production_day_reminder_body)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
