# Generated by Django 3.2.12 on 2023-10-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsetting',
            name='email_port',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
