# Generated by Django 3.2.12 on 2024-02-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientsetting_email_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
