# Generated by Django 3.2.12 on 2022-09-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220731_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
