# Generated by Django 3.2.12 on 2022-08-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
        ('core', '0003_auto_20220731_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
