# Generated by Django 3.2.12 on 2022-03-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='description',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
