# Generated by Django 4.2.11 on 2024-05-20 04:48

from django.db import migrations



def create_uom(apps, schema_editor):
    UOM = apps.get_model('core', 'UOM')
    kg = UOM.objects.create(name='Kilogram', abbreviation='kg', conversion_factor=1.0)
    g = UOM.objects.create(name='Gram', abbreviation='g', base_unit=kg, conversion_factor=0.001)
    lb = UOM.objects.create(name='Pound', abbreviation='lb', base_unit=kg, conversion_factor=0.453592)

def delete_uom(apps, schema_editor):
    UOM = apps.get_model('core', 'UOM')
    UOM.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uom"),
    ]

    operations = [
        migrations.RunPython(create_uom, delete_uom),
        
    ]
