# Generated by Django 4.2.11 on 2024-05-20 04:48

from django.db import migrations



def create_uom(apps, schema_editor):
    UOM = apps.get_model('core', 'UOM')
    g = UOM.objects.create(name='Gram', abbreviation='g', conversion_factor=1)
    kg = UOM.objects.create(name='Kilogram', abbreviation='kg', base_unit=g, conversion_factor=1000)
    lb = UOM.objects.create(name='Pound', abbreviation='lb', base_unit=g, conversion_factor=453.592)

def delete_uom(apps, schema_editor):
    UOM = apps.get_model('core', 'UOM')
    UOM.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uom"),
    ]

    operations = [
        migrations.RunPython(create_uom, delete_uom),
        
    ]
