# Generated by Django 4.2.11 on 2024-08-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_create_uom_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsetting",
            name="is_newsletter_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
