# Generated by Django 3.2.12 on 2022-11-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_host_user', models.CharField(blank=True, max_length=1024, null=True)),
                ('email_port', models.PositiveSmallIntegerField(default=25)),
                ('emaiL_use_tls', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
