# Generated by Django 3.2.12 on 2022-11-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='default_from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
