# Generated by Django 4.2.11 on 2025-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_clientsetting_email_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsetting",
            name="show_login",
            field=models.BooleanField(default=True),
        ),
    ]
