# Generated by Django 3.2.12 on 2022-11-22 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_description'),
        ('core', '0007_clientsetting_default_from_email'),
    ]

    operations = [
    ]
