# Generated by Django 4.2.23 on 2025-12-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_clientsetting_show_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsetting",
            name="account_signup_email_enter_twice",
            field=models.BooleanField(default=False),
        ),
    ]
