# Generated by Django 3.2.12 on 2022-11-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20221122_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='email_subject_prefix',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
