# Generated by Django 3.2.12 on 2022-12-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientsetting_email_subject_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_instagram', models.URLField(blank=True, null=True)),
                ('contact_text', models.TextField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
