# Generated by Django 4.2.23 on 2026-04-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_clientsetting_account_signup_email_enter_twice"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsetting",
            name="custom_css",
            field=models.TextField(
                blank=True,
                help_text="Add custom CSS workshop backend.",
                null=True,
                verbose_name="Custom CSS",
            ),
        ),
    ]
