# Generated by Django 3.2.12 on 2022-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='contact_instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
