# Generated by Django 3.2.12 on 2023-03-16 10:18

import bakeup.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_clientinfo_contact_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmailTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_day_reminder_subject', models.CharField(default='Deine Bestellung ist abholbereit', max_length=1024)),
                ('production_day_reminder_body', models.TextField(default=bakeup.core.models.get_production_day_reminder_body)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
