# Generated by Django 3.2.12 on 2023-03-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clientemailtemplates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientEmailTemplates',
            new_name='ClientEmailTemplate',
        ),
    ]
