# Generated by Django 3.2.12 on 2023-03-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_clientemailtemplates_clientemailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='show_full_name_delivery_bill',
            field=models.BooleanField(default=True),
        ),
    ]
