# Generated by Django 3.2.12 on 2023-04-19 08:28

import bakeup.contrib.fields
import bakeup.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clientsetting_show_full_name_delivery_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='user_registration_fields',
            field=bakeup.contrib.fields.ChoiceArrayField(base_field=models.CharField(choices=[('first_name', 'First name'), ('last_name', 'Last name'), ('point_of_sale', 'Point of sale'), ('street', 'Street'), ('street_number', 'Street number'), ('postal_code', 'Postal code'), ('city', 'City'), ('telephone_number', 'Telephone number')], max_length=24), default=bakeup.core.models.default_registration_fields, size=None),
        ),
    ]
