# Generated by Django 3.2.12 on 2023-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clientsetting_show_full_name_delivery_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='show_remaining_products',
            field=models.BooleanField(default=False),
        ),
    ]
