# Generated by Django 3.2.12 on 2023-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clientsetting_show_remaining_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='language_default',
            field=models.CharField(choices=[('de-DE', 'Deutsch'), ('de-DE-formal', 'Deutsch formal'), ('en', 'Englisch')], default='de-DE', max_length=12),
        ),
    ]
