# Generated by Django 3.2.12 on 2023-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clientsetting_language_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsetting',
            name='email_subject_prefix',
        ),
        migrations.AlterField(
            model_name='clientsetting',
            name='language_default',
            field=models.CharField(choices=[('de', 'Deutsch'), ('de-FL', 'Deutsch formal'), ('en', 'Englisch')], default='de-DE', max_length=12),
        ),
    ]
