# Generated by Django 3.2.12 on 2023-08-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_clientsetting_language_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsetting',
            old_name='emaiL_use_tls',
            new_name='email_use_tls',
        ),
    ]
