# Generated by Django 3.2.12 on 2023-09-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_email_use_tls_clientsetting_email_use_tls'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsetting',
            name='account_email_verification',
            field=models.CharField(choices=[('optional', 'optional'), ('mandatory', 'mandatory'), ('none', 'none')], default='optional', max_length=12),
        ),
    ]
