# Generated by Django 3.2.12 on 2023-10-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='brand_font',
            field=models.CharField(choices=[('d-none', 'Hidden'), ('font-handwriting', 'Handwriting'), ('font-quattrocento', 'Serif (quattrocento)'), ('font-sans-serif', 'Sans Serif')], default='font-handwriting', help_text='Welche Schriftart soll der brand name in der Mobilen ansicht haben?', max_length=17),
        ),
    ]
