# Generated by Django 3.2.12 on 2023-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_generalsettings_brand_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='login_redirect_url',
            field=models.CharField(blank=True, help_text='URL to redirect to after login, should be a relative url starting with a / e.g. /shop/', max_length=1024, null=True),
        ),
    ]
