# Generated by Django 3.2.12 on 2023-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20231107_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='production_day_product_ordering',
            field=models.CharField(choices=[('product__name', 'Alphabetical'), ('?', 'Random'), ('pk', 'Created')], default='product__name', max_length=255),
        ),
    ]
