# Generated by Django 3.2.12 on 2023-05-09 08:10

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230509_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppage',
            name='text_no_production_day',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoppage',
            name='banner_cta',
            field=wagtail.fields.StreamField([('buttons', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Text')), ('link', wagtail.blocks.StructBlock([('target', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock(icon='doc-empty-inverse', label='Page')), ('document', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full', label='Document')), ('image', wagtail.blocks.StructBlock([('alignment', wagtail.blocks.ChoiceBlock(choices=[('start', 'Left'), ('center', 'Centre'), ('end', 'Right')])), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Image')), ('url', wagtail.blocks.URLBlock(label='External link')), ('anchor', wagtail.blocks.CharBlock(help_text='An anchor in the current page, for example: <code>#target-id</code>.', label='Anchor link'))], required=True))], required=True))]))], use_json_field=None, verbose_name='Call to action'),
        ),
    ]
