# Generated by Django 3.2.12 on 2023-05-09 08:25

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('pages', '0005_auto_20230509_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppage',
            name='production_day_limit',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='shoppage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shoppage',
            name='banner_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='shoppage',
            name='text_no_production_day',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='No production days'),
        ),
    ]
