# Generated by Django 3.2.12 on 2023-06-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_checkoutsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutsettings',
            options={'verbose_name': 'Checkout settings'},
        ),
        migrations.AddField(
            model_name='checkoutsettings',
            name='change_order_button',
            field=models.CharField(default='Jetzt kostenpflichtig ändern', max_length=1024),
        ),
        migrations.AddField(
            model_name='checkoutsettings',
            name='place_order_button',
            field=models.CharField(default='Jetzt kostenpflichtig bestellen', max_length=1024),
        ),
    ]
