# Generated by Django 3.2.12 on 2023-06-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20230621_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutsettings',
            old_name='change_order_button',
            new_name='order_button_change',
        ),
        migrations.RenameField(
            model_name='checkoutsettings',
            old_name='place_order_button',
            new_name='order_button_place',
        ),
        migrations.RenameField(
            model_name='checkoutsettings',
            old_name='show_terms',
            new_name='terms_and_conditions_show',
        ),
        migrations.RenameField(
            model_name='checkoutsettings',
            old_name='terms_text',
            new_name='terms_and_conditions_text',
        ),
    ]
