# Generated by Django 4.2.11 on 2024-08-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("pages", "0010_brandsettings_logo_wide_alter_contentpage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandsettings",
            name="logo_wide",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo for wide screens used in newsletter and emails.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Logo wide",
            ),
        ),
    ]
