# Generated by Django 3.2.12 on 2023-06-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20230626_1155'),
        ('pages', '0012_auto_20230622_1156'),
    ]

    operations = [
    ]
