# Generated by Django 4.2.11 on 2024-09-30 12:32

import bakeup.pages.models
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_alter_contentpage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailsettings",
            name="email_order_cancellation",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="Sie haben soeben Ihre komplette Bestellung für den {{ production_day }} gelöscht. Wenn dies ein Versehen war, bestellen Sie die gelöschten Backwaren bitte wieder neu.",
                help_text="Bestellbestätigungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{ order_link }}, {{ point_of_sale }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="email_order_confirm",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="Vielen Dank für Ihre Bestellung, {{ first_name }} {{ last_name }}!\n\nHier eine Übersicht über Ihre Bestellung für den {{ production_day }}:\n\n{{ order }}\n\nGesamtpreis: {{ price_total }}\n\nIhre ausgewählte Abholstelle: {{ point_of_sale }}\n\nSie können Ihre Bestellung vor dem Backtag jederzeit in Ihrem Account unter {{ order_link\xa0}} anpassen oder stornieren.",
                help_text="Bestellbestätigungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{ order_link }}, {{ point_of_sale }}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="production_day_reminder_body",
            field=wagtail.fields.RichTextField(
                default=bakeup.pages.models.get_production_day_reminder_body,
                help_text="Erinnerungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ production_day }}, {{ order_count }}",
            ),
        ),
    ]
