# Generated by Django 3.2.12 on 2023-07-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_merge_0009_auto_20230626_1155_0012_auto_20230622_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsettings',
            name='order_button_cancel',
            field=models.CharField(default='Bestellung komplett stornieren', max_length=1024, verbose_name='Button Bestellung stornieren'),
        ),
        migrations.AlterField(
            model_name='checkoutsettings',
            name='order_button_change',
            field=models.CharField(default='Jetzt verbindlich ändern', max_length=1024, verbose_name='Button Bestellung ändern'),
        ),
    ]
