# Generated by Django 3.2.12 on 2023-08-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20230710_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abo_menu_item', models.CharField(choices=[('never', 'Never'), ('always', 'Always'), ('automatically', 'Automatically')], default='automatically', max_length=13)),
            ],
            options={
                'verbose_name': 'General settings',
            },
        ),
    ]
