# Generated by Django 3.2.12 on 2023-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_generalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='abo_menu_item',
            field=models.CharField(choices=[('never', 'Never'), ('always', 'Always'), ('automatically', 'Automatically')], default='automatically', help_text='Soll der Abo Menüpunkt angezeigt werden?', max_length=13),
        ),
    ]
