# Generated by Django 3.2.12 on 2023-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_generalsettings_abo_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='brand_font',
            field=models.CharField(choices=[('font-handwriting', 'Handwriting'), ('font-quattrocento', 'Serif (quattrocento)'), ('font-sans-serif', 'Sans Serif')], default='font-handwriting', help_text='Welche Schriftart soll der brand name in der Mobilen ansicht haben?', max_length=17),
        ),
    ]
