# Generated by Django 3.2.12 on 2023-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_generalsettings_brand_uppercase'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_footer', models.TextField(blank=True, null=True)),
                ('email_order_confirm', models.TextField(blank=True, help_text='Bestellbestätigungs E-Mail. Mögliche Tags: {{asdf}}', null=True)),
            ],
            options={
                'verbose_name': 'E-Mail settings',
            },
        ),
    ]
