# Generated by Django 3.2.12 on 2023-08-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_emailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_subject_prefix',
            field=models.CharField(default='[{site_name}] ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_footer',
            field=models.TextField(blank=True, help_text='Dieser Footer wird an jede Email angehängt.', null=True),
        ),
    ]
