# Generated by Django 3.2.12 on 2023-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20230822_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='email_subject_prefix',
            field=models.CharField(default='[$site_name] ', help_text='E-Mail-Betreff Präfix, kann $site_name enthalten.', max_length=1024),
        ),
    ]
