# Generated by Django 3.2.12 on 2023-08-22 08:18

import bakeup.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_emailsettings_email_subject_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='production_day_reminder_body',
            field=models.TextField(default=bakeup.pages.models.get_production_day_reminder_body),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='production_day_reminder_subject',
            field=models.CharField(default='Deine Bestellung ist abholbereit', max_length=1024),
        ),
    ]
