# Generated by Django 3.2.12 on 2023-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20230822_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_order_confirm_subject',
            field=models.CharField(default='Vielen Dank für Deine Bestellung', help_text='Betreff kann {{production_day}}, {{order_count}} enthalten.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_subject_prefix',
            field=models.CharField(default='[{{site_name}}]', help_text='E-Mail-Betreff Präfix, kann {{site_name}} enthalten.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='production_day_reminder_subject',
            field=models.CharField(default='Deine Bestellung ist abholbereit', help_text='Betreff kann {{production_day}}, {{order_count}} enthalten.', max_length=1024),
        ),
    ]
