# Generated by Django 3.2.12 on 2023-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20230822_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='send_email_order_confirm',
            field=models.BooleanField(default=False, help_text='Soll eine Bestellbestätigungsmail versendet werden?', verbose_name='Bestellbestätigung versenden?'),
        ),
    ]
