# Generated by Django 3.2.12 on 2023-08-28 08:52

import bakeup.pages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('pages', '0025_auto_20230823_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_order_confirm_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Attachment'),
        ),
    ]
