# Generated by Django 3.2.12 on 2023-08-28 08:52

import bakeup.pages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('pages', '0024_emailsettings_send_email_order_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='email_order_confirm_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_order_confirm',
            field=models.TextField(blank=True, help_text='Bestellbestätigungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ production_day }}, {{ order_count }}, {{ order_link }}', null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_order_confirm_subject',
            field=models.CharField(default='Vielen Dank für Deine Bestellung', help_text='Betreff Bestellbestätigungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ production_day }}, {{ order_count }}, {{ order_link }}', max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='production_day_reminder_body',
            field=models.TextField(default=bakeup.pages.models.get_production_day_reminder_body, help_text='Erinnerungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ production_day }}, {{ order_count }}'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='production_day_reminder_subject',
            field=models.CharField(default='Deine Bestellung ist abholbereit', help_text='Betreff Erinnerungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ production_day }}, {{ order_count }}', max_length=1024),
        ),
    ]
