# Generated by Django 3.2.12 on 2023-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20230825_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppage',
            name='banner_position',
            field=models.CharField(choices=[('top', 'Oben'), ('center', 'Mittig'), ('end', 'Unten')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='email_order_confirm',
            field=models.TextField(blank=True, help_text='Bestellbestätigungs E-Mail. Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{ order_link }}, {{ point_of_sale }}', null=True),
        ),
    ]
