# Generated by Django 3.2.12 on 2023-09-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20230829_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppage',
            name='show_production_day',
            field=models.BooleanField(default=True, verbose_name='Produktionstag anzeigen?'),
        ),
        migrations.AlterField(
            model_name='shoppage',
            name='banner_position',
            field=models.CharField(choices=[('top', 'Oben'), ('center', 'Mittig'), ('end', 'Unten')], default='center', max_length=10, verbose_name='Banner Inhalt Position'),
        ),
    ]
