# Generated by Django 4.2.11 on 2024-05-20 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uom"),
        ("workshop", "0002_create_meta_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.uom",
            ),
        ),
    ]
