# Generated by Django 3.2.12 on 2022-03-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20220324_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='workshop.product'),
        ),
    ]
