# Generated by Django 3.2.12 on 2022-05-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
    ]
