# Generated by Django 4.2.11 on 2024-05-20 05:03

from django.db import migrations

def set_uom(apps, schema_editor):
    UOM = apps.get_model('core', 'UOM')
    g = UOM.objects.get(abbreviation='g')
    Product = apps.get_model('workshop', 'Product')
    Product.objects.update(uom=g)

def unset_uom(apps, schema_editor):
    Product = apps.get_model('workshop', 'Product')
    Product.objects.update(uom=None)


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0003_product_uom"),
    ]

    operations = [
        migrations.RunPython(set_uom, unset_uom),
    ]
