# Generated by Django 4.2.11 on 2024-09-30 12:32

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0004_set_product_uom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindermessage",
            name="body",
            field=wagtail.fields.RichTextField(
                help_text="Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{ point_of_sale }}"
            ),
        ),
    ]
