# Generated by Django 3.2.12 on 2022-05-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
