# Generated by Django 3.2.12 on 2022-05-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_product_product_template'),
        ('workshop', '0005_alter_category_options'),
    ]

    operations = [
    ]
