# Generated by Django 4.2.11 on 2024-10-24 13:46

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0005_alter_remindermessage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remindermessage",
            name="body",
            field=wagtail.fields.RichTextField(
                help_text="Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ order_link }}, {{ order_link_text }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{ point_of_sale }}"
            ),
        ),
    ]
