# Generated by Django 3.2.12 on 2022-03-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20220329_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
