# Generated by Django 4.2.11 on 2024-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0006_alter_remindermessage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bio_certified",
            field=models.BooleanField(default=False, verbose_name="Is bio certified?"),
        ),
    ]
