# Generated by Django 3.2.12 on 2022-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_merge_20220517_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
