# Generated by Django 3.2.12 on 2022-04-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='workshop.product'),
        ),
        migrations.DeleteModel(
            name='ProductRevision',
        ),
    ]
