# Generated by Django 3.2.12 on 2022-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20220517_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight in grams', max_digits=10, null=True),
        ),
    ]
