# Generated by Django 4.2.11 on 2024-11-06 18:08

import bakeup.workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0007_product_is_bio_certified"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[bakeup.workshop.models.validate_video_file],
            ),
        ),
    ]
