# Generated by Django 3.2.12 on 2022-04-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthierarchy',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
