# Generated by Django 3.2.12 on 2022-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_alter_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume_units',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_units',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='weight in grams', null=True),
        ),
    ]
