# Generated by Django 4.2.23 on 2025-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshop", "0008_product_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_order_qty",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Max order quantity?"
            ),
        ),
    ]
