# Generated by Django 3.2.12 on 2022-04-25 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_producthierarchy_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='producthierarchy',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='productionplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.productionplan'),
        ),
        migrations.AddConstraint(
            model_name='productionplan',
            constraint=models.CheckConstraint(check=models.Q(('pk', django.db.models.expressions.F('parent_plan')), _negated=True), name='production_plan_not_equal_parent'),
        ),
    ]
