# Generated by Django 5.2.17 on 2026-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0009_product_max_order_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="checked_ingredients",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
