# Generated by Django 3.2.12 on 2022-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_alter_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ('-start_date',)},
        ),
    ]
