# Generated by Django 3.2.12 on 2022-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_auto_20220425_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
