# Generated by Django 3.2.12 on 2022-04-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_alter_productionplan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
