# Generated by Django 3.2.12 on 2022-09-15 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_customerorderposition_order'),
        ('workshop', '0011_alter_productionplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workshop.productionplan'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='workshop.product'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='production_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='shop.productionday'),
        ),
    ]
