# Generated by Django 5.2.17 on 2026-10-08 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshop", "0012_set_missing_product_uom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_buyable",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_composable",
        ),
    ]
