# Generated by Django 3.2.12 on 2022-09-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_auto_20220915_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ('-production_day', 'product__name')},
        ),
    ]
