# Generated by Django 3.2.12 on 2022-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_alter_productionplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
