# Generated by Django 3.2.12 on 2022-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_alter_productionplan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='state',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Production'), (2, 'Produced'), (3, 'Canceled')], default=0),
        ),
    ]
