# Generated by Django 3.2.12 on 2022-04-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_auto_20220426_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
