# Generated by Django 3.2.12 on 2022-10-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_productionplan_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='state',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'In Production'), (2, 'Produced'), (3, 'Canceled')], default=0),
        ),
    ]
