# Generated by Django 3.2.12 on 2022-11-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_plans', to='workshop.product'),
        ),
    ]
