# Generated by Django 3.2.12 on 2022-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0018_alter_productionplan_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
