# Generated by Django 3.2.12 on 2023-01-12 15:45

from django.db import migrations


def create_meta_category(apps, schema_editor):
    Category = apps.get_model("workshop", "Category")
    if not Category.objects.filter(name='META PRODUCTS').exists():
        latest_category = Category.objects.filter(depth=1).order_by('path').last()
        if not latest_category:
            path = "0001"
        else:
            path_number = int(latest_category.path[3]) + 1
            path = f"{path_number:0>4}"
        Category.objects.create(
            name="META PRODUCTS",
            slug="meta-products",
            path=path,
            depth=1,
            numchild=0,
        )

def remove_meta_category(apps, schema_editor):
    Category = apps.get_model("workshop", "Category")
    Category.objects.filter(name__iexact='META PRODUCTS').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_auto_20221212_1357'),
    ]

    operations = [
        migrations.RunPython(create_meta_category, remove_meta_category),
    ]
