# Generated by Django 3.2.12 on 2023-01-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_meta_category_20230112_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.productionplan')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_product', to='workshop.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_product', to='workshop.product')),
            ],
            options={
                'ordering': ('production_plan__production_day',),
            },
        ),
    ]
