# Generated by Django 3.2.12 on 2023-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_productmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmapping',
            name='matched_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
