# Generated by Django 3.2.12 on 2023-01-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20230113_1013'),
        ('workshop', '0022_productmapping_matched_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmapping',
            options={'ordering': ('production_day',)},
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='production_plan',
        ),
        migrations.AddField(
            model_name='productmapping',
            name='production_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productionday'),
        ),
    ]
