# Generated by Django 3.2.12 on 2023-03-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20230113_1013'),
        ('workshop', '0023_auto_20230119_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmapping',
            name='production_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_mapping', to='shop.productionday'),
        ),
    ]
