# Generated by Django 3.2.12 on 2023-05-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0025_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
