# Generated by Django 3.2.12 on 2023-05-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0026_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
    ]
