# Generated by Django 3.2.12 on 2023-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0027_remove_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_secondary',
            field=models.FileField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
