# Generated by Django 3.2.12 on 2023-06-26 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0028_remindermessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remindermessage',
            options={'ordering': ['-sent_date']},
        ),
        migrations.AddField(
            model_name='remindermessage',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
