# Generated by Django 3.2.12 on 2023-06-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0028_product_image_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
