# Generated by Django 3.2.12 on 2023-06-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0029_auto_20230626_1155'),
        ('workshop', '0030_alter_product_sku'),
    ]

    operations = [
    ]
