# Generated by Django 3.2.12 on 2023-06-26 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop', '0031_merge_0029_auto_20230626_1155_0030_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anzeige name'),
        ),
        migrations.AlterField(
            model_name='remindermessage',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
