# Generated by Django 3.2.12 on 2023-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0032_auto_20230626_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU'),
        ),
    ]
