# Generated by Django 3.2.12 on 2023-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0033_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='max_recurring_order_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
