# Generated by Django 3.2.12 on 2023-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0034_auto_20230627_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is abo product?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_recurring_order_qty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Max abo quantity?'),
        ),
    ]
