# Generated by Django 3.2.12 on 2023-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0039_auto_20230823_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1000, help_text='weight in grams', verbose_name='Weight'),
        ),
    ]
