# Generated by Django 3.2.12 on 2023-08-23 17:31

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0040_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_secondary',
            field=models.FileField(blank=True, null=True, upload_to='product_images', verbose_name='Secondary Image'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=14, verbose_name='Price'),
        ),
    ]
