# Generated by Django 3.2.12 on 2023-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0041_auto_20230823_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction',
            field=models.TextField(blank=True, null=True, verbose_name='Instruction'),
        ),
    ]
