# Generated by Django 3.2.12 on 2023-09-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0042_alter_instruction_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermessage',
            name='body',
            field=models.TextField(help_text='Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{\xa0point_of_sale }}'),
        ),
    ]
