# Generated by Django 3.2.12 on 2023-10-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0043_alter_remindermessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindermessage',
            name='body',
            field=models.TextField(help_text='Mögliche Tags: {{ site_name }}, {{ first_name }}, {{ last_name }}, {{ email }}, {{ order }}, {{ price_total }}, {{ production_day }}, {{ order_count }}, {{ point_of_sale }}'),
        ),
        migrations.AlterField(
            model_name='remindermessage',
            name='state',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'Sent'), (2, 'Planned Sending'), (3, 'Sending')], default=0),
        ),
    ]
