# Generated by Django 5.2.17 on 2026-10-08 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contrib", "0002_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ("created",)},
        ),
    ]
