# Generated by Django 4.2.11 on 2024-06-28 06:40

import bakeup.core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtail_newsletter_simple_smtp", "0001_initial"),
        ("wagtail_newsletter", "0001_initial"),
        ("wagtailcore", "0093_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "newsletter_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject for the newsletter. Defaults to page title if blank.",
                        max_length=1000,
                    ),
                ),
                ("newsletter_campaign", models.CharField(blank=True, max_length=1000)),
                ("author", models.CharField(blank=True, max_length=255)),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Publishing date"
                    ),
                ),
                ("body", bakeup.core.fields.StreamField(blank=True)),
                (
                    "newsletter_audience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="wagtail_newsletter_simple_smtp.audience",
                    ),
                ),
                (
                    "newsletter_recipients",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtail_newsletter.newsletterrecipients",
                    ),
                ),
                (
                    "newsletter_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages",
                        to="wagtail_newsletter_simple_smtp.audiencesegment",
                    ),
                ),
            ],
            options={
                "permissions": [("sendnewsletter_articlepage", "Can send newsletter")],
            },
            bases=("wagtailcore.page",),
        ),
    ]
