# Generated by Django 4.2.11 on 2024-07-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "wagtail_newsletter_simple_smtp",
            "0002_alter_newsletterrecipientsbase_audience_and_more",
        ),
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterpage",
            name="newsletter_recipients",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtail_newsletter_simple_smtp.newsletterrecipients",
            ),
        ),
    ]
