# Generated by Django 4.2.11 on 2024-07-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtail_newsletter_simple_smtp", "0008_remove_audiencesegment_filter_query"),
        ("newsletter", "0002_alter_newsletterpage_newsletter_recipients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "audiencesegment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtail_newsletter_simple_smtp.audiencesegment",
                    ),
                ),
                ("filter_query", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "abstract": False,
            },
            bases=("wagtail_newsletter_simple_smtp.audiencesegment",),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtail_newsletter_simple_smtp.contact",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtail_newsletter_simple_smtp.contact",),
        ),
    ]
