# Generated by Django 4.2.11 on 2024-08-25 17:54

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Contact = apps.get_model("newsletter", "Contact")
    for row in Contact.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])



class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_contact_uuid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
