# Generated by Django 4.2.11 on 2024-08-25 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_generate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
