# Generated by Django 4.2.11 on 2024-09-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0007_contact_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="audiences",
            field=models.ManyToManyField(
                related_name="contacts", to="newsletter.audience"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="audience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contact",
                to="newsletter.audience",
            ),
        ),
    ]
