# Generated by Django 4.2.11 on 2024-09-02 08:27

from django.db import migrations

def make_many_audiences(apps, schema_editor):
    Contact = apps.get_model('newsletter', 'Contact')

    for contact in Contact.objects.all():
        contact.audiences.add(contact.audience)


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0008_contact_audiences_alter_contact_audience"),
    ]

    operations = [
        migrations.RunPython(make_many_audiences),
    ]
