# Generated by Django 4.2.11 on 2024-11-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0010_remove_contact_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterpage",
            name="show_unsubscribe_link",
            field=models.BooleanField(
                default=True,
                help_text="If checked the footer contains an unsbscribe link.",
            ),
        ),
    ]
